<h1>Events</h1>

<p><a href="<?php echo $this->url('zfcadmin/events/crud', array('action' => 'add'))?>">Add new event</a></p>

<?php if (count($this->events) > 0) { ?>
<table class="table table-bordered table-hover table-striped">
    <thead>
        <tr>
            <th>ID</th>
            <th>Event name</th>
            <th>When</th>
            <th>Where</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        <?php foreach($this->events as $event) {?>
        <tr>
            <td><?php echo $event->getId()?></td>
            <td><a href="<?php echo $this->url('zfcadmin/events/crud', array('action' => 'edit', 'id' => $event->getId()))?>"><?php echo $event->getTitle()?></a></td>
            <td>When</td>
            <td>Where</td>
            <td></td>
        </tr>
        <?php } ?>
    </tbody>
</table>
<?php } ?>