<div class="rounded-box-title box">
    <div class="title">
        <h3>Popular Tags</h3>
    </div>
    <div class="box-inner">
        <ul class="tags">
        <?php

            foreach($this->tags as $tag){
                $tagName= $tag['name'];
                $conferenceCount = $tag['counter'];
         ?>
           <li>
                <a class="tagbutton" href="/conferences?tags=<?php echo $tagName?>"><?php echo $tagName?></a>
                <span class="number">x <?php echo $conferenceCount?></span>
           </li>

         <?php
            }
        ?>
        </ul>
    </div>
 </div>
