<?php 
$this->headTitle('Event list');
$this->headLink()->appendStylesheet('/js/jslider/jslider.css')
                 ->appendStylesheet('/js/jslider/jslider.blue.css')
                 ->appendStylesheet('/js/jslider/jslider.ie6.css', array('conditional' => 'lt IE 6'))
                 ->appendStylesheet('/js/jslider/jslider.blue.ie6.css', array('conditional' => 'lt IE 6'));

$this->headScript()->appendFile('/js/jslider/jquery.dependClass.js')
                   ->appendFile('/js/jslider/jquery.slider-min.js');
?>
<div class="wrap">
      <div class="full-width">
        <div class="title-page">
        <div class="border-bottom">
          <hgroup class="clearfix">
          <h2><strong>Event List</strong></h2>
          <h3>Right side controls allow you to refine results. <br>Events can be ordered by date or relevance (based on tags).</h3>
          </hgroup>
          </div>
        </div>
        
        
        <section id="content" class="fl">
          <div class="conferences clearfix">
           <div class="events-head clearfix">
           	<h4><strong><?php echo $this->plurify($this->count,"Event");?></strong></h4>
            <div class="order-by">
            </div>
           </div>
          	<?php 
          		echo $this->partial('partials/conference.phtml', array('conferences' => $this->conferences)); 
          	?>
          
          </div>
          <!-- END: conferences --> 
          <div>
              <?php echo $this->paginatorByperiod($this->periodParam);?>              
          </div>
       
         
        </section>
        <!-- END: content -->
        <!-- START: sidebar -->
        <aside id="sidebar" class="fr">
            
            <?php echo $this->searchForm(); ?>
            <?php echo $this->tagList();?>
        </aside>
        <!-- END: sidebar -->
      </div>
    </div>
