<?php
   $this->headScript()->appendFile("/js/jquery-ui-1.10.3.custom.min.js")
                      ->appendFile("/js/jquery.general.js");
   $this->headLink()->appendStylesheet('/css/ui-lightness/jquery-ui-1.10.3.custom.min.css');                      
?>
<div class="wrap">
  <div class="full-width">
    <div class="title-page">
    <div class="border-bottom">
      <hgroup class="clearfix centered-block">
      <h2 class="centered"><strong>Promote Your Event</strong></h2>
      <h3 class="centered">Let all <strong>HubMe.In</strong> users worldwide know about your event. 
      Just fill the blanks below.</h3>
      </hgroup>
      </div>
    </div>
 
    <section id="content" class="fl">
        <?php 
            $this->form->setAttributes(array(
                'action' => $this->url('conferences/process'),
                'class'=>'promote-form'  )
             );
            $this->form->prepare();

            echo $this->form()->openTag($this->form); 
            //@TOFIX writing <?php echo instead <?= we wrote 112 more character
        ?>
        
        <div><?php echo $this->renderFormRow('email',$this->form); ?></div>
        <div><?php echo $this->renderFormRow('title',$this->form); ?></div>
        <div><?php echo $this->renderFormRow('dateFrom',$this->form); ?></div>
        <div><?php echo $this->renderFormRow('dateTo',$this->form); ?></div>
        <div><?php echo $this->renderFormRow('mainsite',$this->form); ?></div>
        <div><?php echo $this->renderFormRow('abstract',$this->form); ?></div>
        <div><?php echo $this->renderFormRow('tags',$this->form); ?></div>
        <div class="extra">
            <div><?php echo $this->renderFormRow('address',$this->form); ?></div>
            <div><?php echo $this->renderFormRow('city',$this->form) ?></div>
            <div><?php echo $this->renderFormRow('venue',$this->form) ?></div>
            <div><?php echo $this->renderFormRow('twitteraccount',$this->form) ?></div>
            <div><?php echo $this->renderFormRow('twitterhashtag',$this->form) ?></div>
            <div><?php echo $this->renderFormRow('logo',$this->form) ?></div>
        </div>
        <div class="centered"><?php echo $this->renderFormRow('captcha',$this->form) ?></div>
        <div class="centered refreshcaptcha">
            <span><a class="refresh-captcha" href="<?php echo $this->url("form-operations")?>">Unreadable Code? Click here to generate a new one</a></span>
        </div>
        <div class="centered"><?php echo $this->renderFormRow('submit',$this->form) ?></div>
        <?php echo $this->form()->closeTag($this->form); ?>
    </section>
    <!-- END: content -->
    <aside id="sidebar" class="fr">
        <div class="rounded-box-title box">
            <div class="title">
                <h3>Does it seem complex?</h3>
            </div>
            <div class="box-inner">
                <p> Only fields marked with an * are mandatory (there are just 5 of them). You still don't like this form? We'll be happy to fix it. Just... </p>
                <p class="more-wrap">
                    <a class="more" href="/feedback">Let us know</a>
                </p>
            </div>
        </div>
    </aside>
  </div>
</div>
