<footer id="footer">
    <div class="wrap">
    <div class="footer-content">
    
      <div class="copyright-link first">
        <div>&copy;2013 <a href="<?php echo $this->url('home'); ?>" class="site">Hubme.in</a>. All Rights Reserved </div>
        <ul>
          <li><a href="<?php echo $this->url('about'); ?>">About</a></li>
        </ul>
      </div>
      
      <div class="social">
        <ul class="">
          <li class="twitter"><a href="https://twitter.com/hubmein">Follow Us</a></li>
          <li class="facebook"><a href="https://www.facebook.com/hubme.in">Like Us</a></li>
        </ul>
      </div>
      <div class="footer-link">
        <ul>
          <li><a href="<?php echo $this->url('events'); ?>">Attend</a></li>
          <li><a href="<?php echo $this->url('events/promote'); ?>">Promote</a></li>
        </ul>
      </div>
      
    </div>
    
    </div> <!-- END: wrap--> 
  </footer>