<footer id="footer">
    <div class="wrap">
    <div class="footer-content">
    
      <div class="copyright-link first">
        <div>&copy;2013 <a href="#" class="site">Hubme.in</a>. All Rights Reserved </div>
        <ul>
          <li><a href="#">About</a></li>
          <li><a href="#">Give Us Feedback</a></li>
          <li><a href="#">FAQ</a></li>
        </ul>
      </div>
      
      <div class="social">
        <ul class="">
          <li class="twitter"><a href="#">Follow Us</a></li>
          <li class="facebook"><a href="#">Like Us</a></li>
        </ul>
      </div>
      <div class="footer-link">
        <ul>
          <li><a href="#">Attend</a></li>
          <li><a href="#">Speak</a></li>
          <li><a href="#">Promote</a></li>
        </ul>
      </div>
      
    </div>
    
    </div> <!-- END: wrap--> 
  </footer>