<ul class="main-nav">
    <?php
    
    $currentDate = strtolower(date('F-Y'));
    
    foreach($this->container as $page){
           
        $periodFilter = ($page->hasDate) ? "?period=" . $currentDate : "";
        $active = ($page->isActive()) ? "class='current'" : "";
                
        echo "<li " . $active . "><a href='" . $page->getHref() . $periodFilter . "'>" . $page->getLabel() . "</a></li>";
        
     } ?>
</ul>
   