<?php echo $this->doctype(); ?>

<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
<?php 
//title
echo $this->headTitle('Hubme.in')->setSeparator(' | ')->setAutoEscape(false);

//meta
echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0');

//styles
echo $this->headLink()->prependStylesheet('/css/open-sans/stylesheet.css')
                      ->prependStylesheet('/css/select2.css')
                      ->prependStylesheet('/css/style.css')
                      ->prependStylesheet('/css/custom.css');
                     

?>

 <style type="text/css" media="all">
    /* fix rtl for demo */
    .chzn-rtl .chzn-search { left: -9000px; }
    .chzn-rtl .chzn-drop { left: -9000px; }
</style>

</head>
<body id="about">
<div id="page">
  <div class="header-top">
    <div class="wrap">
      <ul class="top-menu">
        <li><a href="<?php echo $this->url('about'); ?>" title="About Hubme.in">About</a></li>
      </ul>
    </div>
  </div>
  <header id="header" class="clearfix">
    <div class="wrap">
      <h1 id="logo"><a href="<?php echo $this->url('home'); ?>"></a></h1>
      <?php echo $this->partial('partials/mainmenu.phtml'); ?>
    </div>
  </header>
  <!-- END: header-->
  
  <div id="main-content" class="clearfix">

            <?php echo $this->content; ?>
</div>
  <!-- END: main-->
  <?php echo $this->partial('partials/footer.phtml'); ?>
  <!-- END: main--> 
  
</div>
<!-- END: page-->

</body>
    
<?php
//js
echo $this->headScript()->prependFile('/js/jquery-1.8.2.js')
                        ->appendFile('/js/css3-mediaqueries.js')
                        ->appendFile('/js/html5.js')
                       
?>

</html>
            



    

