<h1>Edit image for conference <?php echo $this->conference->getTitle()?></h1>

<div>
<?php 

$form = $this->form;
$fileElement = $form->get('image');
$submitElement = $form->get('submit');

$form->prepare();

// open form tag
echo $this->form()->openTag($form);

?>
    <div class="control-group">
        <?php echo $this->formLabel($fileElement); ?>
        <div class="controls">
            <?php
            echo $this->formElement($fileElement); 
            echo $this->formElementErrors($fileElement);
            ?>
            (only .JPG images allowed with a size of 90x90 pixel)
        </div>
    </div>
    
    <div class="control-group">
        <div class="controls">
            <?php echo $this->formElement($submitElement); ?>
        </div>
    </div>
    
<?php 
// close form tag
echo $this->form()->closeTag($form);
?>
</div>