<?php

namespace Events\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * RegionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RegionRepository extends EntityRepository
{
    
    public function getList() {
        
        $queryBuilder = $this->_em->createQueryBuilder();
        
         $result =   $queryBuilder->select("r")
                     ->from($this->_entityName, "r")
                     ->orderBy("r.name ","ASC")
                     ->getQuery()
                     ->getResult();
      
        return $result;
        
    }
     
      
}
