<?php

namespace Events\Entity\Repository;

use Doctrine\ORM\EntityRepository;

<<<<<<< HEAD
/**
 * RegionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RegionRepository extends EntityRepository
{
=======
class RegionRepository extends EntityRepository {
        
>>>>>>> working EventFilter, filtered dql
}
