<div class="wrap">
  <div class="full-width">
    <div class="title-page">
    <div class="border-bottom">
      <hgroup class="clearfix centered-block">
      <h2 class="centered"><strong>Promote Your Event</strong></h2>
      <h3 class="centered">Let all <strong>HubMe.In</strong> users worldwide know about your event. 
      Just fill the blanks below.</h3>
      </hgroup>
      </div>
    </div>
 
    <section id="content" class="fl">
    	<form action="<?php echo $this->url('events/process')?>" method="post" id="promote-form">
    	<?php 
    	
    	$elements = $this->form->getElements();
    	foreach($elements as $element) { 
            echo '<div>' . $this->formRow($element) . '</div>' . "\n";
        } 
        
        ?>
    	</form>
    </section>
    <!-- END: content -->
    
    <aside id="sidebar" class="fr">
      <div class="rounded-box-title box">
        <div class="title">
          <h3>Is there something missing here?</h3>
        </div>
        <div class="box-inner">
        <p>Tell us about your event. We'll publish it on this website (after a quick review)</p>
        <p class="more-wrap"><a href="#" class="more">Get In Touch</a></p>
        </div>
      </div><!-- END: box -->
     
    </aside>
    <!-- END: sidebar -->
    
  </div>
</div>
