    <?php $this->headTitle('Your Simple One Stop for Best Upcoming Conferences') ?>
    <div class="wrap">
      <div class="full-width">
        <div class="title-page">
        <div class="border-bottom">
          <hgroup class="clearfix">
          <h2><strong>About</strong></h2>
          <h3>A standard static page.</h3>
          </hgroup>
          </div>
        </div>
     
        <section id="content" class="fl">
        <div class="about">
        	<div class="attendees service clearfix">
            	<figure><img src="/images/attendees_icon.png" alt="Attendees" ></figure>
            	<div class="service-info">
                	<h3>For Attendees</h3>
                	<p>Collect real time, public feedback on all your sessions - check out how speakers and sessions have been received at other similar events. Your event appears in the listings on the site and speakers can claim their talks to get the sessions associated with their profiles. To make adding sessions even quicker (we organize events ourselves and know how much pressure you are under), there is a handy CSV import function (see the importing talks page for more details).</p>
                </div>
            </div>
            <div class="speakers service clearfix">
            	<figure><img src="/images/speaker_icon.png" alt="Speakers" ></figure>
            	<div class="service-info">
                	<h3>For Speakers</h3>
                	<p>Collect real time, public feedback on all your sessions - check out how speakers and sessions have been received at other similar events. Your event appears in the listings on the site and speakers can claim their talks to get the sessions associated with their profiles. To make adding sessions even quicker (we organize events ourselves and know how much pressure you are under), there is a handy CSV import function (see the importing talks page for more details).</p>
                </div>
            </div>
            <div class="organizers service clearfix">
            	<figure><img src="/images/organizers_icon.png" alt="Organizers" ></figure>
            	<div class="service-info">
                	<h3>For Organizers</h3>
                	<p>Collect real time, public feedback on all your sessions - check out how speakers and sessions have been received at other similar events. Your event appears in the listings on the site and speakers can claim their talks to get the sessions associated with their profiles. To make adding sessions even quicker (we organize events ourselves and know how much pressure you are under), there is a handy CSV import function (see the importing talks page for more details).</p>
                </div>
            </div>
        </div>
        </section>
        <!-- END: content -->
        
        <aside id="sidebar" class="fr">
          <div class="rounded-box-title box">
            <div class="title">
              <h3>Is there something missing here?</h3>
            </div>
            <div class="box-inner">
            <p>Tell us about your event. We'll publish it on this website (after a quick review)</p>
            <p class="more-wrap"><a href="#" class="more">Get In Touch</a></p>
            </div>
          </div><!-- END: box -->
         
        </aside>
        <!-- END: sidebar -->
        
      </div>
    </div>
    <!-- END: wrap--> 