<?php $this->headTitle('Your Simple One Stop for Best Upcoming Conferences') ?>
<div class="wrap">
      <div class="full-width">
        <div class="intro-message">
        <div class="border-bottom">
          <h2>Your reference for the <strong>best events</strong> in the IT industry<br />We make sure you don't miss them.</h2>
          </div>
        </div>
        <div id="feature" class="columns clearfix">
          <h2>Why should I hub.in?</h2>
          <div class="first rounded-background">
            <figure><img src="images/attendees_icon.png" /></figure>
            <h3>Attendees</h3>
            <p>Find upcoming events easily Syndicate or receive a digest of stuff you're interested in Find out what riends of yours also come to conferences, so to ravel together.</p>
            <div class="button"><a href="/events" class="bigbutton">Ok, take me to the conferences!</a></div>
          </div>
          <div class="rounded-background">
            <figure><img src="images/speaker_icon.png" /></figure>
            <h3>Speaker</h3>
            <p>Quickly find out about Call For Papers Syndicate or receive a monthly digest with Call For Paper.</p>
            <div class="button"><a href="#" class="bigbutton">Nice words, I want to speak now!</a></div>
          </div>
          <div class="rounded-background">
            <figure><img src="images/organizers_icon.png" /></figure>
            <h3>Organizers</h3>
            <p>Let best speakers and many attendees now about your conference Track how much expectation it causes Have your conference pop up on joind.in</p>
            <div class="button"><a href="#" class="bigbutton">Ok, I&rsquo;m in. Show me how.</a></div>
          </div>
        </div>
        <!-- END: columns -->
        
        <section id="content" class="fl">
         <div class="conferences clearfix">
            <h2>Right now you should be on your way to:</h2>
          <?php 
          /* We can use a partial from another module here! */
          echo $this->partial('partials/events.phtml', array('events' => $this->events)); 
          ?>
         <div class="more"><a href="/events" class="bigbutton">Find Out More Great Events...</a></div>
		</div>
		<!-- END: conferences --> 
          
        </section>
        <!-- END: content -->
        
        <?php echo $this->rightSideBar(); ?>
        
      </div>
    </div>
