<?php

namespace Conferences\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * TagRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TagRepository extends EntityRepository
{
  
    public function fetchAllPopularTag($activeCfps,$orderBy = 'counter DESC') {
		
                $conditionCol = "dateto";
                $conditionQuery = "";
                
                if($activeCfps){
                    $conditionCol = "cfpclosingdate";
                    $conditionQuery = 'AND (c.cfpclosingdate is not null) ';
                 }
            
		$dql = 'SELECT t.name, COUNT(c) as counter '.
                       'FROM '.$this->_entityName.' t '.
                       'JOIN t.conferences c '.
                       'WHERE c.'.$conditionCol.' >= CURRENT_DATE() '.
                       $conditionQuery.
                       'AND c.isVisible = TRUE '.
                       'GROUP BY t.id '.
                       'ORDER BY ' . $orderBy;
				
		$result = $this->getEntityManager()
                            ->createQuery( $dql )
                            ->getResult(2);
                              
                return $result;
		
	}
    
   
}
