<?php 
if (count($this->events) == 0) {
?>
<div class="event clearfix">
	<div class="event-info">
		<h3>No events happening in selected country soon.</h3>
		<p>Please use select control on right to pick a different one.</p>
</div>

<?php
}
?>

<?php foreach ($this->events as $event) { ?>
<div class="event clearfix">
	<figure class="event-logo"><a href="#"><img src="/images/default_icon.jpg" /></a></figure>
	<div class="event-info">
		<h3><a href="/event?id=<?php echo $event->getId(); ?>"><?php echo $event->getTitle(); ?></a></h3>
		<div class="meta"><?php echo $event->getDatefrom()->format("d/m/Y"); ?> - <?php echo $event->getDateto()->format("d/m/Y"); ?> 
		<strong>(<?php echo $event->getCity(); ?>, <?php echo $event->getCountryName(); ?> )</strong></div>
		<div class="cost"><?php echo $this->cost($event->getAveragedayfee()); ?>
		</div>
		<div class="description">
			<p><?php echo $event->getAbstract(); ?></p>
		</div>
	</div>
</div>
<?php } ?>