<?php

    $this->headLink()->appendStylesheet('/css/search_style.css');
    
    $this->headScript() ->appendFile('/js/select2.min.js')
                        ->appendFile('/js/search.js');
    
                          
?>

<!-- START: box -->
<div class="rounded-box-title box">
    <div class="box-inner clearfix">
         
         <div class="more-wrap">
            <a class="more reset-filters">Clear filters</a>
         </div>

        <form name="search" action="" method="get" class="sidebar-form">
            
            <div>
               <label for="location-1">Topics: </label>
                <select  class="topics" multiple="" tabindex="-1"  >
                    <?php
                    //@TODO Decide how to render loop inside partial
                    foreach( $this->tags as $tagName ) {
                    ?>
                    <option value="<?php echo $tagName; ?>" ><?php echo $tagName; ?></option>
                    <?php
                    }
                    ?>
                </select>

                <p class="type-condition">
                     <input type="radio" checked="true" value="all" name="tc">All <input type="radio" value="alo" name="tc"> At least one
                </p> 
            </div>
            <div>
               <label for="location-1">Location: </label>
               <select name="region" class="regions">
                    <option value="*" >All regions</option>
                    <?php
                     foreach ( $this->regions as $region ) {
                           $selected = ( $this->currentRequest['region'] == $region->getSlug() ) ? "selected" : "";
                    ?>
                    <option value="<?php echo $region->getSlug(); ?>" <?php echo $selected ?> > <?php echo $region->getName(); ?></option>
                     <?php                       
                       }
                     ?>
               </select>
             </div>
             <div>
                  <label for="location-1">Period: </label>
                  <select name="period" class="periods">
                     <option value="*" >All periods</option>

                     <?php
                        foreach( $this->periods as $period) {
                           
                                   $formattedDate = $period["month_year"]->format("F-Y");
                                   $selected = ( $this->currentRequest['period'] == $formattedDate ) ? "selected" : "";
                     ?>
                     <option value="<?php echo $formattedDate?>" <?php echo $selected; ?>><?php echo str_replace("-"," ",$formattedDate) ?></option>
                     <?php
                        }  
                     ?>
                     </select>
             </div>
             <div class="loader"></div>
             <div class="count-loader"></div>
             <div class="submit-loader"></div>
             <div>
                 <input type="submit" class="bigbutton refine" value="Refine">
             </div>
            </form>
      </div>
 </div>
<!-- END: box -->
                
            